/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/075L3YgzPzr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import HeroComponent from "./img"
import Link from "next/link"
import BoxReveal from "./magicui/box-reveal"
import Services from "./Services"

export function Hero() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-8 lg:px-12 h-20 flex items-center">
      <Link href="#" className="flex items-center justify-center" prefetch={false}>
      <img 
        className="h-16 w-auto object-cover object-center"
        src="/1.png"
        alt="Pulp logo"
        style={{ 
          objectPosition: '50% 50%',
          transform: 'scale(2.03)'
        }}
      />
          <span className="sr-only">Pulp</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Services
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-16 lg:py-32 flex items-center justify-center">
          <div className="container px-3 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 items-center">
              <div className="flex flex-col justify-center space-y-4">
              
              <div className="space-y-2">
                <BoxReveal>
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    From raw sound to juicy Pulp
                  </h1>
                </BoxReveal>
                <BoxReveal>
                  <h2 className="text-2xl font-semibold sm:text-4xl xl:text-5xl/none">
                    Squeeze every drop of audio potential.
                  </h2>
                </BoxReveal>
                <BoxReveal>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Transforming audio across all media - from stereo to Dolby Atmos mixing and mastering
                  </p>
                </BoxReveal>
              </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#ff6b00] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#e65c00] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Get a Quote
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-[#ff6b00] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Explore Services
                  </Link>
                </div>
              </div>
              <div className="flex items-center justify-center">
                <HeroComponent />
              </div>

            </div>
          </div>
        </section>

        <Services />
        <section id="about" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">About Sonic Maestros</h2>
                <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Pulp is a team of passionate sound engineers dedicated to delivering exceptional audio
                  experiences. With years of industry experience, we specialize in a wide range of audio services, from
                  music production to podcast editing, ensuring your projects sound their absolute best.
                </p>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="About"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              />
            </div>
          </div>
        </section>
        <section id="contact" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get in Touch</h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Ready to elevate your audio projects? Contact us today to discuss your needs and get a personalized
                quote.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-2">
                <div className="grid gap-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter your name" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Enter your message" />
                </div>
                <Button type="submit" className="bg-[#ff6b00] text-white hover:bg-[#e65c00]">
                  Get a Quote
                </Button>
              </form>
              <p className="text-xs text-muted-foreground">We'll get back to you within 1 business day.</p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Sonic Maestros. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

